# expect:
# SECTION 1: int arithmetic
# 5 6 42 3 2 1024
# -4 3
# 3 15 2 -6 16 16
# 5 -5
# 6
# SECTION 2: float arithmetic
# 4.0 5.5 3.0 3.5
# 3.5
# 4 3
# 1.5
# SECTION 3: comparisons
# True True True False True True
# True False True
# True True
# SECTION 4: bool and None
# True False None
# False True False
# True
# None
# SECTION 5: strings
# hello world
# h d hello world hello
# 11
# HELLO WORLD hello world
# hello there
# ['hello', 'world']
# a-b-c
# True True
# padded
# 42 3.14 True None
# hello world
# 3
# SECTION 6: lists
# [1, 2, 3, 4, 5]
# 1 5 [2, 3] [1, 2] [3, 4, 5]
# 5
# [1, 2, 3, 4, 5, 6]
# [1, 2, 3, 4, 5]
# [5, 4, 3, 2, 1]
# [1, 2, 3, 4, 5]
# 15 5 1
# [2, 4, 6, 8, 10]
# [2, 4]
# True False
# [1, 2, 3, 4, 5, 6, 7]
# [1, 2, 3]
# [3, 2, 1]
# SECTION 7: dicts
# 1 2
# 3
# ['a', 'b', 'c', 'd']
# [1, 2, 3, 4]
# True False
# [('a', 1), ('b', 2), ('c', 3), ('d', 4), ('x', 10)]
# 1 None -1
# SECTION 8: sets
# ['a', 'b', 'c', 'd']
# ['b', 'c']
# ['a']
# True False True True False
# True False
# ['a', 'b', 'c', 'd']
# SECTION 9: tuples
# (1, 'two', 3.0)
# 1 two 3.0
# 1 two 3.0
# SECTION 10: control flow
# 10
# 5
# 0 1 2 4 5 
# 0 0
# 1 0
# 2 0
# SECTION 11: functions
# 5
# hello world
# hello there
# 55
# positive negative zero
# SECTION 12: classes
# Point(3, 4)
# 25
# 10
# Generic makes a sound
# Rex barks
# SECTION 13: exceptions
# caught zero division
# caught index error
# no error here
# finally ran
# caught: n cannot be zero
# SECTION 14: builtins
# 5 5 5.5
# 42 3 3.14 42.0
# False True False True
# A 65
# True True False
# True False
# True False
# True
# DONE

# Comprehensive codegen coverage test.
#
# One large program exercising broad language/codegen surface in a single
# file, restricted to asmpython's supported subset (no generators, no
# multiple inheritance, no decorators beyond @staticmethod/@property, no
# walrus-in-comprehension, etc.) so it runs IDENTICALLY under real CPython
# and under asmpython. The `# expect:` block above is generated by actually
# running this file with `py` (real CPython), not hand-transcribed - the
# whole point is to catch codegen bugs that a hand-written expected-output
# block would silently encode as "correct" too (see the set <=/>= bug found
# 2026-06-19, where codegen produced a result a human transcribing by hand
# might not have caught either).
#
# Organized into numbered sections printing a "SECTION N: name" header so a
# diff against real Python output points at roughly which area regressed.

# ---- Section 1: int arithmetic ----
print("SECTION 1: int arithmetic")
print(2 + 3, 10 - 4, 6 * 7, 17 // 5, 17 % 5, 2 ** 10)
print(-17 // 5, -17 % 5)  # floor semantics: -4, 3
print(7 & 3, 7 | 8, 7 ^ 5, ~5, 1 << 4, 256 >> 4)
print(-(-5), -(5))
a = 10
a += 5
a -= 3
a *= 2
a //= 4
print(a)

# ---- Section 2: float arithmetic ----
print("SECTION 2: float arithmetic")
print(2.5 + 1.5, 10.0 - 4.5, 6.0 * 0.5, 7.0 / 2.0)
print(1.5 + 2)  # int/float promotion
print(round(3.7), round(3.2))
x = 1.0
x += 0.5
print(x)

# ---- Section 3: comparisons and chained comparisons ----
print("SECTION 3: comparisons")
print(1 < 2, 2 <= 2, 3 > 2, 2 >= 3, 1 == 1, 1 != 2)
print(1 < 2 < 3, 1 < 2 < 1, 3 > 2 > 1)
print(1.5 < 2.5, 2.5 == 2.5)

# ---- Section 4: bool / None ----
print("SECTION 4: bool and None")
print(True, False, None)
print(True and False, True or False, not True)
b = True
print(b)
n = None
print(n)

# ---- Section 5: strings ----
print("SECTION 5: strings")
s = "hello" + " " + "world"
print(s)
print(s[0], s[-1], s[0:5], s[6:], s[:5])
print(len(s))
print(s.upper(), s.lower())
print(s.replace("world", "there"))
print(s.split(" "))
print("-".join(["a", "b", "c"]))
print(s.startswith("hello"), s.endswith("world"))
print("  padded  ".strip())
print(str(42), str(3.14), str(True), str(None))
name = "world"
print(f"hello {name}")
print(f"{1 + 2}")

# ---- Section 6: lists ----
print("SECTION 6: lists")
xs = [1, 2, 3, 4, 5]
print(xs)
print(xs[0], xs[-1], xs[1:3], xs[:2], xs[2:])
print(len(xs))
xs.append(6)
print(xs)
xs.pop()
print(xs)
xs.reverse()
print(xs)
xs.sort()
print(xs)
print(sum(xs), max(xs), min(xs))
print([n * 2 for n in xs])
print([n for n in xs if n % 2 == 0])
print(3 in xs, 99 in xs)
ys = xs + [6, 7]
print(ys)
print(sorted([3, 1, 2]))
print(list(reversed([1, 2, 3])))

# ---- Section 7: dicts ----
print("SECTION 7: dicts")
d = {"a": 1, "b": 2, "c": 3}
print(d["a"], d["b"])
print(len(d))
d["d"] = 4
print(sorted(d.keys()))
print(sorted(d.values()))
print("a" in d, "z" in d)
d2 = {"x": 10}
d.update(d2)
print(sorted(d.items()))
print(d.get("a"), d.get("zzz"), d.get("zzz", -1))

# ---- Section 8: sets ----
print("SECTION 8: sets")
s1 = {"a", "b", "c"}
s2 = {"b", "c", "d"}
print(sorted(s1 | s2))
print(sorted(s1 & s2))
print(sorted(s1 - s2))
s3 = {"a"}
print(s3 <= s1, s1 <= s3, s3 < s1, s1 <= s1, s1 < s1)
print(s1 >= s3, s3 >= s1)
s1 |= s2
print(sorted(s1))

# ---- Section 9: tuples ----
print("SECTION 9: tuples")
t = (1, "two", 3.0)
print(t)
print(t[0], t[1], t[2])
a2, b2, c2 = t
print(a2, b2, c2)

# ---- Section 10: control flow ----
print("SECTION 10: control flow")
total = 0
for i in range(5):
    total += i
print(total)

i = 0
while i < 5:
    i += 1
print(i)

for i in range(10):
    if i == 3:
        continue
    if i == 6:
        break
    print(i, end=" ")
print()

for i in range(3):
    for j in range(3):
        if j == 1:
            break
        print(i, j)

# ---- Section 11: functions ----
print("SECTION 11: functions")


def add(a, b):
    return a + b


def greet(name="world"):
    return f"hello {name}"


def fib(n):
    if n <= 1:
        return n
    return fib(n - 1) + fib(n - 2)


print(add(2, 3))
print(greet())
print(greet("there"))
print(fib(10))


def multi_return(x):
    if x > 0:
        return "positive"
    elif x < 0:
        return "negative"
    else:
        return "zero"


print(multi_return(5), multi_return(-5), multi_return(0))

# ---- Section 12: classes ----
print("SECTION 12: classes")


class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __str__(self):
        return f"Point({self.x}, {self.y})"

    def magnitude_sq(self):
        return self.x * self.x + self.y * self.y


p = Point(3, 4)
print(p)
print(p.magnitude_sq())
p.x = 10
print(p.x)


class Animal:
    def __init__(self, name):
        self.name = name

    def speak(self):
        return f"{self.name} makes a sound"


class Dog(Animal):
    def speak(self):
        return f"{self.name} barks"


generic = Animal("Generic")
rex = Dog("Rex")
print(generic.speak())
print(rex.speak())

# ---- Section 13: exceptions ----
print("SECTION 13: exceptions")
try:
    result = 10 / 0
except ZeroDivisionError:
    print("caught zero division")

try:
    idx_list = [1, 2, 3]
    print(idx_list[10])
except IndexError:
    print("caught index error")

try:
    print("no error here")
except Exception:
    print("should not print")
finally:
    print("finally ran")


def risky(n):
    if n == 0:
        raise ValueError("n cannot be zero")
    return 100 // n


try:
    risky(0)
except ValueError as e:
    print(f"caught: {e}")

# ---- Section 14: builtins ----
print("SECTION 14: builtins")
print(abs(-5), abs(5), abs(-5.5))
print(int("42"), int(3.9), float("3.14"), float(42))
print(bool(0), bool(1), bool(""), bool("x"))
print(chr(65), ord("A"))
print(isinstance(5, int), isinstance("x", str), isinstance(5, str))
print(any([False, False, True]), any([False, False]))
print(all([True, True]), all([True, False]))
print(hash(5) == hash(5))

print("DONE")
