"""The C backend: portable source, every register a local.

READ THIS FIRST IF YOU ARE WRITING A BACKEND.

This is a complete, correct backend in about two hundred lines, and it is
deliberately the dumbest one that works. Every virtual register becomes a local
variable; there is no register allocation, no liveness, no instruction
selection. It emits C because a C compiler then handles the parts that are
genuinely hard and genuinely uninteresting -- calling conventions, stack
frames, relocation -- so this file can show only the part you actually have to
understand: how to walk the IR.

The shape below is the shape of every backend:

    for each function
        emit a prologue                     declare the registers
        for each block
            emit a label
            for each instruction
                switch on ins.op            <- the whole job
        emit an epilogue

A machine backend replaces "declare a C local" with "assign a stack slot or a
register" and "emit a C expression" with "emit an instruction". The traversal
never changes.

WHAT THIS BACKEND DOES NOT DO, ON PURPOSE
-----------------------------------------
It never allocates a register. Giving every value its own slot is always
correct; allocation is an optimisation, and `ir.regalloc` is there when you
want it. Starting with allocation is how a backend ends up subtly wrong in
ways that only appear under register pressure, which is exactly the hardest
case to debug.
"""
from __future__ import annotations

from ...ir import types as T
from ...backend.base import Backend, register
from ...ir.module import Function, Instruction, Module
from ...ir.opcodes import Op

#: IR type -> C type. `ptr` is an integer so pointer arithmetic needs no casts;
#: `i1` is 8-bit because that is how the IR stores it.
_CTYPE = {
    T.I1: "int8_t", T.I8: "int8_t", T.I16: "int16_t",
    T.I32: "int32_t", T.I64: "int64_t",
    T.U8: "uint8_t", T.U16: "uint16_t", T.U32: "uint32_t", T.U64: "uint64_t",
    T.F32: "float", T.F64: "double",
    T.PTR: "uintptr_t", T.VOID: "void",
}

_BIN = {
    Op.ADD: "+", Op.SUB: "-", Op.MUL: "*", Op.DIV: "/", Op.REM: "%",
    Op.AND: "&", Op.OR: "|", Op.XOR: "^", Op.SHL: "<<", Op.SHR: ">>",
    Op.EQ: "==", Op.NE: "!=", Op.LT: "<", Op.LE: "<=", Op.GT: ">", Op.GE: ">=",
}

_PRELUDE = """\
/* Generated by the `naive` backend. Compile with any C99 compiler. */
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>

/* The host functions the IR may call. A frontend emits calls to these by
   name; a real target would resolve them from a runtime library. */
static void print_int(int64_t v) { printf("%lld\\n", (long long)v); }
static void print_float(double v) { printf("%f\\n", v); }
static void print_str(uintptr_t p) { fputs((const char *)p, stdout); }
static int  putchar_(int64_t c) { return putchar((int)c); }
"""

#: Host functions defined by the prelude above. Any OTHER external the module
#: declares gets an `extern` declaration generated from its IR signature --
#: without one, C assumes `int f()`, and a call to a function returning double
#: reads the wrong register and produces a plausible wrong number instead of
#: any kind of error.
_PROVIDED = {"print_int", "print_float", "print_str", "putchar"}


class CBackend(Backend):
    name = "c"
    description = "portable C99 source; one local per register, no allocation"
    default_target = "c"
    #: The emitted C defines its own `main` and its own host functions.
    self_contained = True

    def emit(self, module: Module, target) -> dict[str, bytes]:
        out: list[str] = [_PRELUDE]

        for g in module.globals:
            out.append(_global(g))
        if module.globals:
            out.append("")

        # Forward declarations, so call order in the module never matters.
        for f in module.functions:
            if f.external:
                if f.name not in _PROVIDED:
                    out.append("extern " + _signature(f) + ";")
            else:
                out.append(_signature(f) + ";")
        out.append("")

        for f in module.functions:
            if not f.external:
                out.append(self._func(f))
                out.append("")

        # An IR function called `main` is not C's `main`: C requires `int
        # main(void)` and the IR's may return i64 or take parameters. Emitting
        # it directly is a compile error, so it is renamed (see _cname) and a
        # real entry point wraps it. Without this the output looks correct and
        # fails at the C compiler, which is a confusing place to learn about it.
        if module.function("main") is not None:
            out.append("int main(void) { return (int)ir_main(); }")
            out.append("")

        return {"out.c": "\n".join(out).encode("utf-8")}

    # ── one function ────────────────────────────────────────────────────────
    def _func(self, fn: Function) -> str:
        L = [_signature(fn) + " {"]

        # Every register becomes a local. Declared up front and zeroed: a C
        # compiler warns about a "maybe uninitialised" local even where the IR
        # verifier has proved the read is safe, and the zeroing costs nothing
        # a C optimiser will not remove.
        for reg in sorted(fn.registers):
            if reg in fn.params:
                continue
            L.append(f"    {_CTYPE[fn.registers[reg]]} r{reg} = 0;")

        for blk in fn.blocks:
            L.append(f"{_label(blk.label)}:;")
            for ins in blk.instructions:
                L.append("    " + self._instr(fn, ins))

        L.append("}")
        return "\n".join(L)

    # ── one instruction: the whole job ──────────────────────────────────────
    def _instr(self, fn: Function, ins: Instruction) -> str:
        op, ty = ins.op, ins.ty
        d = f"r{ins.dst}"
        a = [f"r{x}" for x in ins.args]
        c = _CTYPE[ty]

        match op:
            case Op.CONST:
                return f"{d} = {_lit(ty, ins.imm)};"
            case Op.COPY:
                return f"{d} = {a[0]};"
            case Op.GLOBAL_ADDR:
                return f"{d} = (uintptr_t)g_{_cname(ins.sym)};"
            case Op.FUNC_ADDR:
                return f"{d} = (uintptr_t)&{ins.sym};"

            case Op.REM if ty.is_float:
                # C's `%` does not accept doubles at all, so this was a
                # compile error in the generated source rather than a wrong
                # answer -- the good version of this bug, and still one no
                # test had ever triggered.
                return (f"{d} = {'fmodf' if ty is T.F32 else 'fmod'}"
                        f"({a[0]}, {a[1]});")

            case Op.ADD | Op.SUB | Op.MUL | Op.DIV | Op.REM | Op.AND | Op.OR \
                 | Op.XOR | Op.SHL | Op.SHR:
                # The cast makes C's promotion rules match the IR's: without
                # it, `i8 + i8` is computed in `int` and does not wrap at 8
                # bits, so 127+1 would be 128 rather than -128.
                return f"{d} = ({c})(({c}){a[0]} {_BIN[op]} ({c}){a[1]});"
            case Op.NEG:
                return f"{d} = ({c})(-({c}){a[0]});"
            case Op.NOT:
                return f"{d} = ({c})(~({c}){a[0]});"

            case Op.EQ | Op.NE | Op.LT | Op.LE | Op.GT | Op.GE:
                return f"{d} = (({c}){a[0]} {_BIN[op]} ({c}){a[1]}) ? 1 : 0;"

            case Op.TRUNC | Op.EXTEND | Op.FTOI | Op.ITOF | Op.FTOF:
                return f"{d} = ({c}){a[0]};"
            case Op.BITCAST:
                src = _CTYPE[fn.register_type(ins.args[0])]
                return (f"memcpy(&{d}, &{a[0]}, "
                        f"sizeof({c}) < sizeof({src}) "
                        f"? sizeof({c}) : sizeof({src}));")

            case Op.ALLOCA:
                return f"{d} = (uintptr_t)alloca({ins.imm});"
            case Op.LOAD:
                return f"{d} = *({c} *){a[0]};"
            case Op.STORE:
                return f"*({c} *){a[1]} = ({c}){a[0]};"
            case Op.OFFSET:
                return f"{d} = {a[0]} + (uintptr_t){a[1]};"

            case Op.CALL:
                call = f"{_cname(ins.sym)}({', '.join(a)})"
                return f"{d} = {call};" if ins.dst is not None else f"{call};"
            case Op.CALL_PTR:
                args = ", ".join(a[1:])
                sig = f"{c} (*)({', '.join('int64_t' for _ in a[1:])})"
                call = f"(({sig}){a[0]})({args})"
                return f"{d} = {call};" if ins.dst is not None else f"{call};"

            case Op.JUMP:
                return f"goto {_label(ins.labels[0])};"
            case Op.BRANCH:
                return (f"if ({a[0]}) goto {_label(ins.labels[0])}; "
                        f"else goto {_label(ins.labels[1])};")
            case Op.SWITCH:
                arms = " ".join(
                    f"case {v}: goto {_label(l)};" for v, l in ins.cases)
                return (f"switch ({a[0]}) {{ {arms} "
                        f"default: goto {_label(ins.labels[0])}; }}")
            case Op.RET:
                return f"return {a[0]};" if ins.args else "return;"
            case Op.UNREACHABLE:
                return 'fprintf(stderr, "unreachable\\n"); abort();'

            case _:
                # Not a silent fallthrough. A new opcode must fail loudly here,
                # at build time, rather than emitting nothing and producing a
                # program that is wrong in a way no test names.
                raise NotImplementedError(
                    f"{self.name} backend has no rule for {op.value!r}"
                )


def _signature(fn: Function) -> str:
    params = ", ".join(
        f"{_CTYPE[fn.registers[p]]} r{p}" for p in fn.params) or "void"
    return f"{_CTYPE[fn.ret]} {_cname(fn.name)}({params})"


#: IR symbols that would collide with something C already defines. `main` is
#: renamed and wrapped (see emit); the rest are host functions whose C
#: signatures differ from the IR's.
_RESERVED = {"main": "ir_main", "putchar": "putchar_"}

#: C keywords and the standard type names. A source language has no reason to
#: avoid these -- `def double(n: int)` is perfectly good Python -- and emitting
#: the name verbatim produces `r7 = double(r1);`, which is a C syntax error
#: pointing at generated code the user never wrote. Everything here gets a
#: trailing underscore instead.
_C_KEYWORDS = frozenset("""
auto break case char const continue default do double else enum extern float
for goto if inline int long register restrict return short signed sizeof
static struct switch typedef union unsigned void volatile while
_Bool _Complex _Imaginary _Alignas _Alignof _Atomic _Generic _Noreturn
_Static_assert _Thread_local bool true false NULL
""".split())


def _label(name: str) -> str:
    """A C label for an IR block label.

    Block labels are frontend-chosen and hand-written IR is a documented way
    to test a backend, so nothing stops one being called `default` or
    `switch`. Prefixed rather than suffixed: a label is not a symbol anyone
    links against, so there is no reason to keep it recognisable to a linker,
    and a prefix cannot collide with a keyword at all.
    """
    return "L_" + _cname(name)


def _cname(name: str) -> str:
    """IR symbols may contain characters C does not allow in identifiers."""
    if name in _RESERVED:
        return _RESERVED[name]
    safe = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in name)
    # Two different problems needing two different fixes. A keyword stops
    # being one with any suffix; a leading digit needs a PREFIX, and
    # suffixing `2fast` gives `2fast_`, which is still not an identifier.
    if safe and safe[0].isdigit():
        safe = "n" + safe
    if safe in _C_KEYWORDS:
        safe += "_"
    return safe


def _global(g) -> str:
    if g.data is None:
        return f"static uint8_t g_{_cname(g.name)}[{max(1, g.size)}];"
    body = ", ".join(str(b) for b in g.data)
    const = "const " if g.readonly else ""
    return (f"static {const}uint8_t g_{_cname(g.name)}[{len(g.data)}]"
            f" = {{{body}}};")


def _lit(ty: T.Type, v) -> str:
    if ty.is_float:
        return repr(float(v))
    return f"INT64_C({int(v)})" if ty.size == 8 else str(int(v))


register(CBackend())
