"""Generate `unicode_table.py` from the reference implementation's data.

Beside the table it writes rather than in `tools/`, which holds downloaded
dependencies and is not in the repository -- a generated table nobody can
regenerate is a table nobody can check.

    python -m asmpython.link._gen_unicode

Run when the Unicode version this compiler claims changes. The output is a
list of RUNS of code points sharing a class mask, which is what makes the
table three thousand entries rather than a bit per code point.

ASCII IS NOT IN IT: `apy_str_is` decides those in code, and dropping them
removes the densest and least interesting part of the table.
"""
import pathlib
import unicodedata

CLASSES = ("ALPHA", "DECIMAL", "DIGIT", "NUMERIC", "LOWER", "UPPER", "TITLE",
           "SPACE", "PRINTABLE", "XIDSTART", "XIDCONT")
BIT = {n: 1 << i for i, n in enumerate(CLASSES)}


def mask(cp: int) -> int:
    """Every class this code point belongs to, as a bit set.

    Asked of the reference implementation itself rather than derived from
    categories: `isidentifier` is XID_Start/XID_Continue and not "is a
    letter", and `isprintable` has exceptions a category list does not carry.
    """
    ch = chr(cp)
    m = 0
    if ch.isalpha():
        m |= BIT["ALPHA"]
    if ch.isdecimal():
        m |= BIT["DECIMAL"]
    if ch.isdigit():
        m |= BIT["DIGIT"]
    if ch.isnumeric():
        m |= BIT["NUMERIC"]
    if ch.islower():
        m |= BIT["LOWER"]
    if ch.isupper():
        m |= BIT["UPPER"]
    # THE CATEGORY, not `str.istitle()`. A one-character string of a capital
    # letter IS titlecase to `istitle`, so asking it here gave `'É'` the
    # TITLE bit -- and `isupper` treats a titlecase character as disqualifying,
    # so every accented capital answered False.
    if unicodedata.category(ch) == "Lt":
        m |= BIT["TITLE"]
    if ch.isspace():
        m |= BIT["SPACE"]
    if ch.isprintable():
        m |= BIT["PRINTABLE"]
    # A CONTINUE character is one that may FOLLOW a start character, which is
    # what `("a" + ch).isidentifier()` asks and what no category answers.
    if ("a" + ch).isidentifier():
        m |= BIT["XIDCONT"]
    if ch.isidentifier():
        m |= BIT["XIDSTART"]
    return m


def runs():
    out, prev, start = [], None, 0x80
    for cp in range(0x80, 0x110000):
        m = mask(cp)
        if m != prev:
            if prev:
                out.append((start, cp - 1, prev))
            start, prev = cp, m
    if prev:
        out.append((start, 0x10FFFF, prev))
    return out


def emit(into) -> str:
    entries = runs()
    lines = [
        "/* THE UNICODE CHARACTER CLASSES, as runs of code points.",
        "",
        "   GENERATED by `link/_gen_unicode.py` from the reference",
        "   implementation's own data, not approximated: U+00B2 is numeric and",
        "   not decimal, U+2167 is numeric and not a digit at all, and no rule",
        "   short of the real table gets those right along with the eight other",
        "   predicates that share it.",
        "",
        "   ASCII IS DECIDED IN CODE and the table starts at U+0080, which",
        f"   drops its densest part. {len(entries)} runs remain. */",
    ]
    for i, name in enumerate(CLASSES):
        lines.append("#define APY_UC_%s %uu" % (name, 1 << i))
    lines.append("")
    lines.append("static const struct { unsigned lo, hi, m; } apy_uc[] = {")
    line = "   "
    for lo, hi, m in entries:
        piece = " {%d,%d,%u}," % (lo, hi, m)
        if len(line) + len(piece) > 78:
            lines.append(line)
            line = "   "
        line += piece
    lines.append(line)
    lines.append("};")
    lines.append("""
/* Which classes a code point belongs to. A binary search over the runs, so a
   predicate over a long string is one lookup per character and not a walk. */
static unsigned apy_uc_mask(uint32_t cp) {
    int lo = 0, hi = (int)(sizeof apy_uc / sizeof apy_uc[0]) - 1;
    if (cp < 0x80) return 0;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (cp < apy_uc[mid].lo) hi = mid - 1;
        else if (cp > apy_uc[mid].hi) lo = mid + 1;
        else return apy_uc[mid].m;
    }
    return 0;
}""")
    body = "\n".join(lines) + "\n"
    into.write_text(
        '"""The Unicode character classes, as C.\n\n'
        "GENERATED by `link/_gen_unicode.py`. Its own module because it is\n"
        "sixty kilobytes of table and `objects.py` is meant to be read;\n"
        "`objects.py` splices it in at its marker, so the C that reaches a\n"
        "backend is one file as it always was.\n"
        '"""\n\nUNICODE_C = r"""' + body + '"""\n',
        encoding="utf-8")
    return f"{len(entries)} runs"


if __name__ == "__main__":
    print(emit(pathlib.Path(__file__).resolve().parent / "unicode_table.py"))
