package asmpython.jvm;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;

/**
 * The flat address space asmpython's IR assumes.
 *
 * <p>{@code alloca}, {@code load}, {@code store} and {@code gep} all operate on
 * integer addresses, and the JVM has no such thing — so one is provided here as
 * a {@link ByteBuffer} with a bump allocator, where an "address" is an index
 * into it. That is what lets generated bytecode treat every pointer as an
 * ordinary {@code long} and never touch a JVM reference.
 *
 * <p>Little-endian, to match the x86-64 backend's view of the same IR: the two
 * backends must agree on layout for a value round-tripped through
 * {@code bitcast}, and for the container headers in {@link Containers}, which
 * generated code reads and writes <em>directly</em> rather than only through
 * the ABI.
 *
 * <p>Allocation never reclaims and never reuses, which makes one guarantee the
 * containers rely on: fresh memory is always zero. The native runtime needs a
 * separate {@code _runtime_zalloc} for that; here it is free.
 */
public class Memory {

    protected static final int HEAP_BYTES = 256 * 1024 * 1024;

    protected static final ByteBuffer HEAP =
            ByteBuffer.allocateDirect(HEAP_BYTES).order(ByteOrder.LITTLE_ENDIAN);

    /**
     * The lowest address this heap hands out, and it is not a free choice.
     *
     * <p>The lowering distinguishes a pointer from a small integer by
     * magnitude: {@code PTR_THRESHOLD = 0x10000} in ir_lower.py, and anything
     * below it is read as a raw int rather than dereferenced. On a real malloc
     * that is safe because addresses are large. A bump allocator starting near
     * zero is not — every allocation would look like an integer, and a boxed
     * value would print as its own address instead of its contents.
     *
     * <p>So the base sits an order of magnitude above the threshold. The
     * skipped megabyte costs nothing but virtual space in the buffer, and the
     * margin means a future change to the threshold does not silently break
     * this backend.
     */
    protected static final long HEAP_BASE = 1L << 20;

    /** Address 0 is reserved so a null pointer stays falsy and unusable. */
    private static long brk = HEAP_BASE;

    protected Memory() {
    }

    // ---- allocation ------------------------------------------------------

    public static synchronized long allocate(long bytes) {
        long size = (bytes + 7) & ~7L;          // keep everything 8-aligned
        if (brk + size > HEAP_BYTES) {
            throw new OutOfMemoryError(
                    "asmpython JVM heap exhausted at " + brk + " allocating " + bytes);
        }
        long address = brk;
        brk += size;
        return address;
    }

    /** Backs the IR's {@code alloca}; frames are never reclaimed. */
    public static long alloca(long bytes) {
        return allocate(bytes);
    }

    /** How much of the heap is in use — diagnostics, not a Python-visible value. */
    public static long allocated() {
        return brk;
    }

    // ---- memory ----------------------------------------------------------

    public static long loadLong(long address) {
        return HEAP.getLong(checked(address, 8));
    }

    public static void storeLong(long address, long value) {
        HEAP.putLong(checked(address, 8), value);
    }

    public static double loadDouble(long address) {
        return HEAP.getDouble(checked(address, 8));
    }

    public static void storeDouble(long address, double value) {
        HEAP.putDouble(checked(address, 8), value);
    }

    public static long loadByte(long address) {
        return HEAP.get(checked(address, 1)) & 0xFFL;
    }

    public static void storeByte(long address, long value) {
        HEAP.put(checked(address, 1), (byte) value);
    }

    /**
     * Bounds-check an access, turning a wild address into a diagnosable error.
     *
     * <p>Worth the cost here: a bad pointer is nearly always a codegen bug, and
     * ByteBuffer's own IndexOutOfBounds names neither the address nor the fact
     * that it came from generated code. Address 0 is called out separately
     * because a null dereference is the common case and means something
     * specific.
     */
    protected static int checked(long address, int width) {
        if (address <= 0 || address + width > HEAP_BYTES) {
            throw new IllegalStateException(address == 0
                    ? "asmpython: null pointer dereference"
                    : "asmpython: address " + address + " is outside the heap");
        }
        return (int) address;
    }

    // ---- bit conversions -------------------------------------------------

    public static long doubleToRawLongBits(double value) {
        return Double.doubleToRawLongBits(value);
    }

    public static double longBitsToDouble(long bits) {
        return Double.longBitsToDouble(bits);
    }

    // ---- strings ---------------------------------------------------------
    //
    // A string is a NUL-terminated UTF-8 byte run in the heap, the same shape
    // the native runtime uses, so a pointer means the same thing on both
    // backends. Java Strings appear only at the boundary.

    /** Reads a NUL-terminated UTF-8 string out of the heap. */
    public static String readString(long address) {
        if (address == 0) {
            return "";
        }
        int start = checked(address, 1);
        int end = start;
        while (end < HEAP_BYTES && HEAP.get(end) != 0) {
            end++;
        }
        byte[] raw = new byte[end - start];
        for (int i = 0; i < raw.length; i++) {
            raw[i] = HEAP.get(start + i);
        }
        return new String(raw, StandardCharsets.UTF_8);
    }

    /** Writes a NUL-terminated UTF-8 string at {@code address}; returns it. */
    public static long writeString(long address, String text) {
        byte[] raw = text.getBytes(StandardCharsets.UTF_8);
        int base = checked(address, raw.length + 1);
        for (int i = 0; i < raw.length; i++) {
            HEAP.put(base + i, raw[i]);
        }
        HEAP.put(base + raw.length, (byte) 0);
        return address;
    }

    /** Copies a Java String into fresh heap memory. */
    public static long allocateString(String text) {
        byte[] raw = text.getBytes(StandardCharsets.UTF_8);
        return writeString(allocate(raw.length + 1), text);
    }

    public static long strlen(long address) {
        int i = checked(address, 1);
        while (HEAP.get(i) != 0) {
            i++;
        }
        return i - address;
    }

    /** strdup: the copy a dict makes so it owns its keys. */
    public static long strdup(long address) {
        return allocateString(readString(address));
    }
}
