package asmpython.jvm;

import java.io.PrintStream;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * Runtime support for asmpython's JVM backend.
 *
 * <p>asmpython's IR is built on a flat address space: {@code alloca},
 * {@code load}, {@code store} and {@code gep} all operate on integer
 * addresses. The JVM has no such thing, so one is provided here — a
 * {@link ByteBuffer} with a bump allocator, and an "address" is simply an
 * index into it. That is what lets the generated bytecode treat every
 * pointer as an ordinary {@code long} and never touch a JVM reference.
 *
 * <p>Little-endian, to match the x86-64 backend's view of the same IR: the
 * two backends must agree on layout for a value round-tripped through
 * {@code bitcast}.
 */
public final class Runtime {

    private static final int HEAP_BYTES = 64 * 1024 * 1024;
    private static final ByteBuffer HEAP =
            ByteBuffer.allocateDirect(HEAP_BYTES).order(ByteOrder.LITTLE_ENDIAN);

    /** Address 0 is reserved so a null pointer stays falsy and unusable. */
    private static long brk = 8;

    private static final PrintStream OUT = System.out;

    private Runtime() {
    }

    // ---- allocation ------------------------------------------------------

    public static synchronized long allocate(long bytes) {
        long size = (bytes + 7) & ~7L;          // keep everything 8-aligned
        if (brk + size > HEAP_BYTES) {
            throw new OutOfMemoryError("asmpython JVM heap exhausted at " + brk);
        }
        long address = brk;
        brk += size;
        return address;
    }

    /** Backs the IR's {@code alloca}; frames are never reclaimed. */
    public static long alloca(long bytes) {
        return allocate(bytes);
    }

    // ---- memory ----------------------------------------------------------

    public static long loadLong(long address) {
        return HEAP.getLong((int) address);
    }

    public static void storeLong(long address, long value) {
        HEAP.putLong((int) address, value);
    }

    public static double loadDouble(long address) {
        return HEAP.getDouble((int) address);
    }

    public static void storeDouble(long address, double value) {
        HEAP.putDouble((int) address, value);
    }

    public static long loadByte(long address) {
        return HEAP.get((int) address) & 0xFFL;
    }

    public static void storeByte(long address, long value) {
        HEAP.put((int) address, (byte) value);
    }

    public static long doubleToRawLongBits(double value) {
        return Double.doubleToRawLongBits(value);
    }

    public static double longBitsToDouble(long bits) {
        return Double.longBitsToDouble(bits);
    }

    // ---- strings ---------------------------------------------------------

    /** Reads a NUL-terminated UTF-8 string out of the heap. */
    public static String readString(long address) {
        if (address == 0) {
            return "";
        }
        int start = (int) address;
        int end = start;
        while (end < HEAP_BYTES && HEAP.get(end) != 0) {
            end++;
        }
        byte[] raw = new byte[end - start];
        for (int i = 0; i < raw.length; i++) {
            raw[i] = HEAP.get(start + i);
        }
        return new String(raw, java.nio.charset.StandardCharsets.UTF_8);
    }

    /** Writes a NUL-terminated UTF-8 string at {@code address}; returns it. */
    public static long writeString(long address, String text) {
        byte[] raw = text.getBytes(java.nio.charset.StandardCharsets.UTF_8);
        for (int i = 0; i < raw.length; i++) {
            HEAP.put((int) address + i, raw[i]);
        }
        HEAP.put((int) address + raw.length, (byte) 0);
        return address;
    }

    public static long allocateString(String text) {
        byte[] raw = text.getBytes(java.nio.charset.StandardCharsets.UTF_8);
        return writeString(allocate(raw.length + 1), text);
    }

    public static long strlen(long address) {
        int i = (int) address;
        while (HEAP.get(i) != 0) {
            i++;
        }
        return i - address;
    }

    // ---- ABI helpers the lowering emits ----------------------------------

    /**
     * {@code _abi_int_to_base(value, base, scratch)} — renders an integer,
     * returning a FRESH string rather than writing into {@code scratch}.
     *
     * The lowering passes the same global scratch buffer to every conversion
     * in a statement, so `print(a, b, c)` hands printf three pointers that are
     * all the same address. Writing in place makes every one of them show the
     * last value converted; the native runtime hands back independent results,
     * and this must match it.
     */
    public static long _abi_int_to_base(long value, long base, long scratch) {
        String text = (base == 10)
                ? Long.toString(value)
                : Long.toString(value, (int) base);
        return allocateString(text);
    }

    /**
     * {@code _abi_float_to_str(value)} — renders a float the way CPython's
     * {@code str()} does, which is not what {@link Double#toString} gives:
     * Python prints 12.56636 and 2.0, Java prints 12.56636 and 2.0 but
     * diverges on integral values in exponent range and on trailing zeros.
     */
    public static long _abi_float_to_str(double value) {
        String text;
        if (Double.isNaN(value)) {
            text = "nan";
        } else if (Double.isInfinite(value)) {
            text = value > 0 ? "inf" : "-inf";
        } else if (value == Math.floor(value) && Math.abs(value) < 1e16) {
            text = Long.toString((long) value) + ".0";
        } else {
            text = Double.toString(value);
        }
        return allocateString(text);
    }

    /** {@code _abi_raise(message, code)} — asmpython's error path. */
    public static void _abi_raise(long message, long code) {
        throw new RuntimeException(readString(message));
    }

    // ---- output ----------------------------------------------------------

    public static void printf(long format) {
        OUT.print(format(readString(format), new long[0], new int[0]));
    }

    public static void printf(long format, long a0) {
        OUT.print(format(readString(format), new long[]{a0}, new int[]{0}));
    }

    public static void printf(long format, long a0, long a1) {
        OUT.print(format(readString(format), new long[]{a0, a1}, new int[]{0, 0}));
    }

    public static void printf(long format, long a0, long a1, long a2) {
        OUT.print(format(readString(format), new long[]{a0, a1, a2}, new int[]{0, 0, 0}));
    }

    /**
     * A deliberately small printf: enough of the C format language for what
     * asmpython's lowering actually emits ({@code %s}, {@code %d}/{@code %ld},
     * {@code %c}, {@code %%}), rather than a general implementation.
     */
    private static String format(String spec, long[] args, int[] unusedKinds) {
        StringBuilder out = new StringBuilder();
        int argIndex = 0;
        for (int i = 0; i < spec.length(); i++) {
            char c = spec.charAt(i);
            if (c != '%') {
                out.append(c);
                continue;
            }
            i++;
            if (i >= spec.length()) {
                break;
            }
            // Skip width/length modifiers: %ld, %5d, %zu ...
            while (i < spec.length() && "0123456789lzhu.-+ ".indexOf(spec.charAt(i)) >= 0
                    && "diouxXeEfgGcsp%".indexOf(spec.charAt(i)) < 0) {
                i++;
            }
            if (i >= spec.length()) {
                break;
            }
            char kind = spec.charAt(i);
            long arg = argIndex < args.length ? args[argIndex] : 0L;
            switch (kind) {
                case '%':
                    out.append('%');
                    break;
                case 's':
                    out.append(readString(arg));
                    argIndex++;
                    break;
                case 'c':
                    out.append((char) arg);
                    argIndex++;
                    break;
                case 'f':
                case 'g':
                case 'e':
                    out.append(Double.longBitsToDouble(arg));
                    argIndex++;
                    break;
                case 'x':
                    out.append(Long.toHexString(arg));
                    argIndex++;
                    break;
                default:
                    out.append(arg);
                    argIndex++;
                    break;
            }
        }
        return out.toString();
    }

    public static void puts(long address) {
        OUT.println(readString(address));
    }

    public static void exit(long code) {
        OUT.flush();
        System.exit((int) code);
    }
}
