"""Which builtin methods a kind has, in the machine subset.

GENERATED by `objects/c/_gen_kindmeth.py`. Its own module for the
reason `unicode_table.py` is: it is a table, and the runtime is
meant to be read.
"""


def apy_kind_meth_arity_of(w: ptr, bit: i64) -> i64:
    """The arity of `w` on a receiver of kind `bit`, packed as
    `(most << 8) | nopt`, or 0 for a name that kind does not have.
    """
    if apy_cstr_eq(w, rodata(b"add\0")):
        if bit & 64:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"append\0")):
        if bit & 12:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"as_integer_ratio\0")):
        if bit & 768:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"bit_count\0")):
        if bit & 256:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"bit_length\0")):
        if bit & 256:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"capitalize\0")):
        if bit & 7:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"casefold\0")):
        if bit & 1:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"center\0")):
        if bit & 7:
            return 769
        return 0
    if apy_cstr_eq(w, rodata(b"clear\0")):
        if bit & 108:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"conjugate\0")):
        if bit & 2816:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"copy\0")):
        if bit & 236:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"count\0")):
        if bit & 1055:
            return 1026
        return 0
    if apy_cstr_eq(w, rodata(b"decode\0")):
        if bit & 6:
            return 770
        return 0
    if apy_cstr_eq(w, rodata(b"difference\0")):
        if bit & 192:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"difference_update\0")):
        if bit & 64:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"discard\0")):
        if bit & 64:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"encode\0")):
        if bit & 1:
            return 770
        return 0
    if apy_cstr_eq(w, rodata(b"endswith\0")):
        if bit & 7:
            return 1026
        return 0
    if apy_cstr_eq(w, rodata(b"expandtabs\0")):
        if bit & 7:
            return 513
        return 0
    if apy_cstr_eq(w, rodata(b"extend\0")):
        if bit & 12:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"find\0")):
        if bit & 7:
            return 1026
        return 0
    if apy_cstr_eq(w, rodata(b"format_map\0")):
        if bit & 1:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"get\0")):
        if bit & 32:
            return 769
        return 0
    if apy_cstr_eq(w, rodata(b"hex\0")):
        if bit & 518:
            return 513
        return 0
    if apy_cstr_eq(w, rodata(b"index\0")):
        if bit & 1055:
            return 1026
        return 0
    if apy_cstr_eq(w, rodata(b"insert\0")):
        if bit & 12:
            return 768
        return 0
    if apy_cstr_eq(w, rodata(b"intersection\0")):
        if bit & 192:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"intersection_update\0")):
        if bit & 64:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"is_integer\0")):
        if bit & 768:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"isalnum\0")):
        if bit & 7:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"isalpha\0")):
        if bit & 7:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"isascii\0")):
        if bit & 7:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"isdecimal\0")):
        if bit & 1:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"isdigit\0")):
        if bit & 7:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"isdisjoint\0")):
        if bit & 192:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"isidentifier\0")):
        if bit & 1:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"islower\0")):
        if bit & 7:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"isnumeric\0")):
        if bit & 1:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"isprintable\0")):
        if bit & 1:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"isspace\0")):
        if bit & 7:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"issubset\0")):
        if bit & 192:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"issuperset\0")):
        if bit & 192:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"istitle\0")):
        if bit & 7:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"isupper\0")):
        if bit & 7:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"items\0")):
        if bit & 32:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"join\0")):
        if bit & 7:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"keys\0")):
        if bit & 32:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"ljust\0")):
        if bit & 7:
            return 769
        return 0
    if apy_cstr_eq(w, rodata(b"lower\0")):
        if bit & 7:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"lstrip\0")):
        if bit & 7:
            return 513
        return 0
    if apy_cstr_eq(w, rodata(b"partition\0")):
        if bit & 7:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"pop\0")):
        if bit & 108:
            return 770
        return 0
    if apy_cstr_eq(w, rodata(b"popitem\0")):
        if bit & 32:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"remove\0")):
        if bit & 76:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"removeprefix\0")):
        if bit & 7:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"removesuffix\0")):
        if bit & 7:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"replace\0")):
        if bit & 7:
            return 1025
        return 0
    if apy_cstr_eq(w, rodata(b"resize\0")):
        if bit & 4:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"reverse\0")):
        if bit & 12:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"rfind\0")):
        if bit & 7:
            return 1026
        return 0
    if apy_cstr_eq(w, rodata(b"rindex\0")):
        if bit & 7:
            return 1026
        return 0
    if apy_cstr_eq(w, rodata(b"rjust\0")):
        if bit & 7:
            return 769
        return 0
    if apy_cstr_eq(w, rodata(b"rpartition\0")):
        if bit & 7:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"rsplit\0")):
        if bit & 7:
            return 770
        return 0
    if apy_cstr_eq(w, rodata(b"rstrip\0")):
        if bit & 7:
            return 513
        return 0
    if apy_cstr_eq(w, rodata(b"setdefault\0")):
        if bit & 32:
            return 769
        return 0
    if apy_cstr_eq(w, rodata(b"sort\0")):
        if bit & 8:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"split\0")):
        if bit & 7:
            return 770
        return 0
    if apy_cstr_eq(w, rodata(b"splitlines\0")):
        if bit & 7:
            return 513
        return 0
    if apy_cstr_eq(w, rodata(b"startswith\0")):
        if bit & 7:
            return 1026
        return 0
    if apy_cstr_eq(w, rodata(b"strip\0")):
        if bit & 7:
            return 513
        return 0
    if apy_cstr_eq(w, rodata(b"swapcase\0")):
        if bit & 7:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"symmetric_difference\0")):
        if bit & 192:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"symmetric_difference_update\0")):
        if bit & 64:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"title\0")):
        if bit & 7:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"to_bytes\0")):
        if bit & 256:
            return 1027
        return 0
    if apy_cstr_eq(w, rodata(b"translate\0")):
        if bit & 7:
            return 769
        return 0
    if apy_cstr_eq(w, rodata(b"union\0")):
        if bit & 192:
            return 512
        return 0
    if apy_cstr_eq(w, rodata(b"update\0")):
        if bit & 96:
            return 513
        return 0
    if apy_cstr_eq(w, rodata(b"upper\0")):
        if bit & 7:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"values\0")):
        if bit & 32:
            return 256
        return 0
    if apy_cstr_eq(w, rodata(b"zfill\0")):
        if bit & 7:
            return 512
        return 0
    return 0


def apy_kind_meth_written_of(w: ptr, bit: i64) -> i64:
    """Does CPython WRITE this dunder out for a receiver of kind
    `bit`, rather than filling a slot with it? That is the whole of
    what tells `builtin_function_or_method` from `method-wrapper`.
    """
    if apy_cstr_eq(w, rodata(b"__alloc__\0")):
        if bit & 4:
            return 1
        return 0
    if apy_cstr_eq(w, rodata(b"__bytes__\0")):
        if bit & 2:
            return 1
        return 0
    if apy_cstr_eq(w, rodata(b"__ceil__\0")):
        if bit & 768:
            return 1
        return 0
    if apy_cstr_eq(w, rodata(b"__class_getitem__\0")):
        if bit & 248:
            return 1
        return 0
    if apy_cstr_eq(w, rodata(b"__complex__\0")):
        if bit & 2048:
            return 1
        return 0
    if apy_cstr_eq(w, rodata(b"__contains__\0")):
        if bit & 224:
            return 1
        return 0
    if apy_cstr_eq(w, rodata(b"__dir__\0")):
        if bit & 4095:
            return 1
        return 0
    if apy_cstr_eq(w, rodata(b"__floor__\0")):
        if bit & 768:
            return 1
        return 0
    if apy_cstr_eq(w, rodata(b"__format__\0")):
        if bit & 4095:
            return 1
        return 0
    if apy_cstr_eq(w, rodata(b"__getformat__\0")):
        if bit & 512:
            return 1
        return 0
    if apy_cstr_eq(w, rodata(b"__getitem__\0")):
        if bit & 40:
            return 1
        return 0
    if apy_cstr_eq(w, rodata(b"__getnewargs__\0")):
        if bit & 2835:
            return 1
        return 0
    if apy_cstr_eq(w, rodata(b"__getstate__\0")):
        if bit & 4095:
            return 1
        return 0
    if apy_cstr_eq(w, rodata(b"__init_subclass__\0")):
        if bit & 4095:
            return 1
        return 0
    if apy_cstr_eq(w, rodata(b"__new__\0")):
        if bit & 4095:
            return 1
        return 0
    if apy_cstr_eq(w, rodata(b"__reduce__\0")):
        if bit & 4095:
            return 1
        return 0
    if apy_cstr_eq(w, rodata(b"__reduce_ex__\0")):
        if bit & 4095:
            return 1
        return 0
    if apy_cstr_eq(w, rodata(b"__reversed__\0")):
        if bit & 1064:
            return 1
        return 0
    if apy_cstr_eq(w, rodata(b"__round__\0")):
        if bit & 768:
            return 1
        return 0
    if apy_cstr_eq(w, rodata(b"__sizeof__\0")):
        if bit & 4095:
            return 1
        return 0
    if apy_cstr_eq(w, rodata(b"__subclasshook__\0")):
        if bit & 4095:
            return 1
        return 0
    if apy_cstr_eq(w, rodata(b"__trunc__\0")):
        if bit & 768:
            return 1
        return 0
    return 0
