"""Generate the builtin-method table, as C and as the machine subset.

Beside the tables it writes rather than in `tools/`, for the reason
`_gen_unicode.py` gives: a generated table nobody can regenerate is a table
nobody can check.

    python -m asmpython.objects.c._gen_kindmeth

WHAT IT IS FOR. `"abc".upper` is lowered at the CALL SITE by the frontend, so
it exists as a call and never as an attribute -- and
`getattr("abc", "upper")` was an AttributeError about a method the object
plainly has. Anything dispatching by method NAME saw a builtin as having
none: `operator.methodcaller`, a plugin table, `getattr(x, name)(...)`.

TWO QUESTIONS AND TWO ANSWERS, and both are generated because both are
already written down somewhere else:

  WHICH KINDS OWN A NAME is CPython's own `hasattr`, asked over the twelve
  builtin types at generation time. Transcribing it by hand is how a table
  comes to claim that a list has `keys`.

  WHICH SYMBOL SERVES AN ARITY is `DYN_METHOD_TABLE`, which the frontend
  already uses to lower the written form. Reading it here is what makes the
  two spellings ONE implementation rather than two that can drift.

THE ARITY IS THE UNION over the owners, deliberately. `str.count` takes a
window and `list.count` does not, and the table has one entry per NAME -- so
the native admits the widest form and the symbol it reaches refuses a
receiver it cannot serve, exactly as the written form already does.

SEVEN CALL SHAPES ARE IRREGULAR and are mirrored from `_dyn_builtin_method`:
`keys`/`values`/`items` take an int selector, `pop` under two arguments takes
a had-index flag, `encode`/`decode` always take three, `hex`/`expandtabs`
with none take a filled second, `get`/`setdefault` with one take a None
default, `sort` takes its two keywords as values, and `update` takes a dict.
"""
import pathlib
import sys

#: The twelve builtin types a receiver can be, and the bit each gets. The
#: NAMES are what `apy_kind_attr_of` already computes for the receiver in
#: hand; the bits are private to the generated pair.
KINDS = ["str", "bytes", "bytearray", "list", "tuple", "dict", "set",
         "frozenset", "int", "float", "range", "complex"]

#: Names the generated table must NOT claim, because something above it
#: answers them first and differently. `index` and `count` reach
#: `apy_index_of`/`apy_count_of`, which split on the receiver themselves;
#: the rest are answered by hand in `apy_kind_attr_of` for kinds the table
#: cannot see (a range's `start`, a generator's `send`).
SKIP = {"send", "throw", "close", "setter", "getter", "indices", "subgroup",
        "add_note", "fromhex"}


#: A name whose real arity range is NOT the one `DYN_METHOD_TABLE` shows.
#: `to_bytes` has ONE entry point taking all three parameters, because two of
#: them have defaults and `signed` is keyword-only -- so the table shows 3..3
#: where Python accepts nought to three, and the lowering pads. The dispatch
#: below pads the same way; see `call_shape`.
ARITY_OVERRIDE = {"to_bytes": (0, 3)}


def owners():
    """Every non-dunder method name, with the kinds that own it and the
    arities `DYN_METHOD_TABLE` serves."""
    from asmpython.frontends.python.methods import DYN_METHOD_TABLE
    types = {"str": str, "bytes": bytes, "bytearray": bytearray,
             "list": list, "tuple": tuple, "dict": dict, "set": set,
             "frozenset": frozenset, "int": int, "float": float,
             "range": range, "complex": complex}
    out = []
    for name in sorted(DYN_METHOD_TABLE):
        if name.startswith("__") or name in SKIP:
            continue
        kinds = [k for k in KINDS if hasattr(types[k], name)]
        if not kinds:
            continue
        syms = DYN_METHOD_TABLE[name]
        live = [i for i, s in enumerate(syms) if s is not None]
        if not live:
            continue
        lo, hi = ARITY_OVERRIDE.get(name, (min(live), max(live)))
        out.append((name, kinds, lo, hi,
                    [syms[i] if i < len(syms) else None
                     for i in range(max(live) + 1)]))
    return out


def mask(kinds) -> int:
    return sum(1 << KINDS.index(k) for k in kinds)


def emit_c(rows) -> str:
    """The C half: one arity lookup and one dispatch."""
    lines = [
        "/* WHICH BUILTIN METHODS A KIND HAS, and which runtime entry point",
        "   serves each arity.",
        "",
        "   GENERATED by `objects/c/_gen_kindmeth.py` from CPython's own",
        "   `hasattr` and from the frontend's `DYN_METHOD_TABLE`. See that",
        f"   file for why. {len(rows)} names.",
        "",
        "   THE BITS MATCH `KINDS` there and are private to this pair. */",
    ]
    for i, k in enumerate(KINDS):
        lines.append(f"#define APY_MK_{k.upper()} {1 << i}u")
    lines += [
        "",
        "/* The arity of `w` on a receiver of kind `bit`, packed as",
        "   `(most << 8) | nopt`, or 0 for a name that kind does not have. */",
        "static int64_t apy_kind_meth_arity(const char *w, unsigned bit) {",
    ]
    for name, kinds, lo, hi, _ in rows:
        lines.append(f'    if (strcmp(w, "{name}") == 0)')
        lines.append(f"        return (bit & {mask(kinds)}u) "
                     f"? (({hi + 1} << 8) | {hi - lo}) : 0;")
    lines += ["    return 0;", "}", ""]

    lines += emit_signatures(rows)

    lines += [
        "/* One builtin method call, by name and by the count that arrived.",
        "   The irregular shapes are mirrored from `_dyn_builtin_method`; see",
        "   the generator. Answers 0 having raised for an arity no entry",
        "   point serves, which is how a receiver's own kind refuses a form",
        "   another kind admits. */",
        "static apy_value apy_kind_meth_call(const char *w, apy_value *a,",
        "                                    int64_t n) {",
    ]
    for name, kinds, lo, hi, syms in rows:
        lines.append(f'    if (strcmp(w, "{name}") == 0) {{')
        for argc in range(hi, lo - 1, -1):
            sym = syms[argc] if argc < len(syms) else None
            if name in ARITY_OVERRIDE:
                sym = syms[hi]
            if sym is None:
                continue
            lines.append(f"        if (n >= {argc + 1}) return "
                         + call_shape(name, sym, argc) + ";")
        lines.append("    }")
    lines += [
        '    return apy_fail2("TypeError", "\'%s\' is not a builtin method%s",',
        '                     w, "");',
        "}",
    ]
    return "\n".join(lines) + "\n"


def call_shape(name, sym, argc) -> str:
    """The arguments one entry point takes, which is not always `a[0..argc]`.

    SEVEN OF THEM ARE IRREGULAR and every one is mirrored from the frontend's
    `_dyn_builtin_method`: the two spellings have to reach the same call.
    """
    if name in ("keys", "values", "items"):
        part = {"keys": 0, "values": 1, "items": 2}[name]
        return f"apy_dict_parts(a[0], {part})"
    if name == "pop" and argc < 2:
        if argc == 0:
            return f"{sym}(a[0], apy_none(), 0)"
        return f"{sym}(a[0], a[1], 1)"
    if name in ("encode", "decode"):
        args = ", ".join(["a[0]"] + [f"a[{i + 1}]" if i < argc else "apy_none()"
                                     for i in range(2)])
        return f"{sym}({args})"
    if name in ("hex", "expandtabs") and argc == 0:
        filled = "apy_from_int(8)" if name == "expandtabs" else "apy_none()"
        return f"{sym}(a[0], {filled})"
    if name in ("get", "setdefault") and argc == 1:
        return f"{sym}(a[0], a[1], apy_none())"
    if name == "sort":
        return f"{sym}(a[0], apy_none(), apy_from_bool(0))"
    if name == "update" and argc == 0:
        return f"{sym}(a[0], apy_dict_new(1))"
    if name == "to_bytes":
        # ONE ENTRY POINT TAKING ALL THREE, padded from the defaults
        # `METHOD_PARAMS` records -- which is what the lowering does for the
        # written form, so the two spellings reach the same call.
        pad = ["apy_from_int(1)", 'apy_lit("big")', "apy_from_bool(0)"]
        args = ["a[0]"] + [f"a[{i + 1}]" if i < argc else pad[i]
                           for i in range(3)]
        return f"{sym}({', '.join(args)})"
    return f"{sym}({', '.join(['a[0]'] + [f'a[{i + 1}]' for i in range(argc)])})"


def c_value(default) -> str:
    """One parameter default as the C that builds it."""
    if default is True or default is False:
        return f"apy_from_bool({1 if default else 0})"
    if default is None:
        return "apy_none()"
    if isinstance(default, int):
        return f"apy_from_int({default})"
    if isinstance(default, str):
        return f'apy_lit("{default}")'
    if default == b"":
        return 'apy_bytes_literal((apy_value)"", 0)'
    raise AssertionError(f"no C for the default {default!r}")


def emit_signatures(rows) -> list:
    """`apy_kind_meth_sign` -- the parameter NAMES a keyword may use.

    THE SAME TABLE THE WRITTEN FORM FOLDS AGAINST. `METHOD_PARAMS` says what
    each of these methods calls its parameters and what each defaults to, and
    the frontend arranges a written `x.split(",", maxsplit=1)` with it. A
    method reached as a VALUE -- `f = x.split` then `f(",", maxsplit=1)`, or
    the collision path handing an int's `to_bytes` to `apy_call_kw` -- has no
    frontend to arrange it, so the names travel on the callable itself and
    the ordinary keyword binder places them. Without this the bound method
    reported `got an unexpected keyword argument` for a call CPython answers.

    A PARAMETER CPYTHON MARKS POSITIONAL-ONLY HAS A NULL NAME, which is what
    keeps it unreachable by keyword while still leaving its slot in place.
    """
    from asmpython.frontends.python.methods import (  # noqa: E402
        METHOD_PARAMS, POSITIONAL_ONLY, REQUIRED)
    arity = {name: hi + 1 for name, _, _, hi, _ in rows}
    lines = [
        "/* THE PARAMETER NAMES A KEYWORD MAY USE, and the value each slot",
        "   defaults to, for the methods CPython gives a keyword signature.",
        "",
        "   GENERATED from `METHOD_PARAMS`, which is the same table the",
        "   frontend folds the WRITTEN spelling against -- so `x.split(\",\",",
        "   maxsplit=1)` and `f = x.split` then `f(\",\", maxsplit=1)` are one",
        "   arrangement rather than two that can drift.",
        "",
        "   Answers the count, or 0 for a name with no keyword signature at",
        "   all. `names[i]` is 0 for a parameter CPython marks positional",
        "   only; `defs[i]` is 0 for one with no default. */",
        "static int64_t apy_kind_meth_sign(const char *w, apy_value *names,",
        "                                  apy_value *defs) {",
    ]
    for name, params in sorted(METHOD_PARAMS.items()):
        # ONLY WHERE THE TWO TABLES AGREE ON THE COUNT. A name whose dispatch
        # arity does not match its signature would put a keyword in the wrong
        # slot, which is worse than not placing it at all.
        if arity.get(name) != len(params) + 1:
            continue
        lines.append(f'    if (strcmp(w, "{name}") == 0) {{')
        for i, (pname, default) in enumerate(params):
            spelled = ("0" if pname is POSITIONAL_ONLY
                       else f'apy_lit("{pname}")')
            filled = "0" if default is REQUIRED else c_value(default)
            lines.append(f"        names[{i}] = {spelled}; "
                         f"defs[{i}] = {filled};")
        lines.append(f"        return {len(params)};")
        lines.append("    }")
    lines += ["    return 0;", "}", ""]
    return lines


def emit_ir(rows) -> str:
    """The ported half: the arity lookup only.

    THE DISPATCH STAYS IN C. `apy_call_nk` is `static` there and serves both
    compiled runtimes, so the call never reaches the subset; only
    `apy_kind_attr_of` does, and all it needs is the arity.

    THE `_of` SUFFIX IS THE TREE'S CONVENTION for an IR twin of a C name: the
    two halves share one translation unit, so a subset function wearing a C
    static's name is a redefinition from gcc rather than a second copy.
    """
    lines = [
        '"""Which builtin methods a kind has, in the machine subset.',
        "",
        "GENERATED by `objects/c/_gen_kindmeth.py`. Its own module for the",
        "reason `unicode_table.py` is: it is a table, and the runtime is",
        "meant to be read.",
        '"""',
        "",
        "",
        "def apy_kind_meth_arity_of(w: ptr, bit: i64) -> i64:",
        '    """The arity of `w` on a receiver of kind `bit`, packed as',
        "    `(most << 8) | nopt`, or 0 for a name that kind does not have.",
        '    """',
    ]
    for name, kinds, lo, hi, _ in rows:
        lines.append(f'    if apy_cstr_eq(w, rodata(b"{name}\\0")):')
        lines.append(f"        if bit & {mask(kinds)}:")
        lines.append(f"            return {((hi + 1) << 8) | (hi - lo)}")
        lines.append("        return 0")
    lines.append("    return 0")
    return "\n".join(lines) + "\n"


def main() -> None:
    here = pathlib.Path(__file__).resolve().parent
    sys.path.insert(0, str(here.parent.parent.parent))
    rows = owners()
    (here / "kindmeth_table.py").write_text(
        '"""The builtin-method table, as C.\n\n'
        "GENERATED by `objects/c/_gen_kindmeth.py`. Its own module for the\n"
        "reason `unicode_table.py` is: it is a table, and `objects.py` is\n"
        'meant to be read.\n"""\n\n'
        'KINDMETH_C = r"""' + emit_c(rows) + '"""\n', encoding="utf-8")
    (here.parent.parent / "runtime" / "kindmeth_table.py").write_text(
        emit_ir(rows), encoding="utf-8")
    print(f"{len(rows)} names")


if __name__ == "__main__":
    main()
