"""The builtin-method table, as C.

GENERATED by `objects/c/_gen_kindmeth.py`. Its own module for the
reason `unicode_table.py` is: it is a table, and `objects.py` is
meant to be read.
"""

KINDMETH_C = r"""/* WHICH BUILTIN METHODS A KIND HAS, and which runtime entry point
   serves each arity.

   GENERATED by `objects/c/_gen_kindmeth.py` from CPython's own
   `hasattr` and from the frontend's `DYN_METHOD_TABLE`. See that
   file for why. 82 names.

   THE BITS MATCH `KINDS` there and are private to this pair. */
#define APY_MK_STR 1u
#define APY_MK_BYTES 2u
#define APY_MK_BYTEARRAY 4u
#define APY_MK_LIST 8u
#define APY_MK_TUPLE 16u
#define APY_MK_DICT 32u
#define APY_MK_SET 64u
#define APY_MK_FROZENSET 128u
#define APY_MK_INT 256u
#define APY_MK_FLOAT 512u
#define APY_MK_RANGE 1024u
#define APY_MK_COMPLEX 2048u
#define APY_MK_MEMORYVIEW 4096u

/* The arity of `w` on a receiver of kind `bit`, packed as
   `(most << 8) | nopt`, or 0 for a name that kind does not have. */
static int64_t apy_kind_meth_arity(const char *w, unsigned bit) {
    if (strcmp(w, "add") == 0)
        return (bit & 64u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "append") == 0)
        return (bit & 12u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "as_integer_ratio") == 0)
        return (bit & 768u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "bit_count") == 0)
        return (bit & 256u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "bit_length") == 0)
        return (bit & 256u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "capitalize") == 0)
        return (bit & 7u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "casefold") == 0)
        return (bit & 1u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "center") == 0)
        return (bit & 7u) ? ((3 << 8) | 1) : 0;
    if (strcmp(w, "clear") == 0)
        return (bit & 108u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "conjugate") == 0)
        return (bit & 2816u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "copy") == 0)
        return (bit & 236u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "count") == 0)
        return (bit & 1055u) ? ((4 << 8) | 2) : 0;
    if (strcmp(w, "decode") == 0)
        return (bit & 6u) ? ((3 << 8) | 2) : 0;
    if (strcmp(w, "difference") == 0)
        return (bit & 192u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "difference_update") == 0)
        return (bit & 64u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "discard") == 0)
        return (bit & 64u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "encode") == 0)
        return (bit & 1u) ? ((3 << 8) | 2) : 0;
    if (strcmp(w, "endswith") == 0)
        return (bit & 7u) ? ((4 << 8) | 2) : 0;
    if (strcmp(w, "expandtabs") == 0)
        return (bit & 7u) ? ((2 << 8) | 1) : 0;
    if (strcmp(w, "extend") == 0)
        return (bit & 12u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "find") == 0)
        return (bit & 7u) ? ((4 << 8) | 2) : 0;
    if (strcmp(w, "format_map") == 0)
        return (bit & 1u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "get") == 0)
        return (bit & 32u) ? ((3 << 8) | 1) : 0;
    if (strcmp(w, "hex") == 0)
        return (bit & 518u) ? ((2 << 8) | 1) : 0;
    if (strcmp(w, "index") == 0)
        return (bit & 1055u) ? ((4 << 8) | 2) : 0;
    if (strcmp(w, "insert") == 0)
        return (bit & 12u) ? ((3 << 8) | 0) : 0;
    if (strcmp(w, "intersection") == 0)
        return (bit & 192u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "intersection_update") == 0)
        return (bit & 64u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "is_integer") == 0)
        return (bit & 768u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "isalnum") == 0)
        return (bit & 7u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "isalpha") == 0)
        return (bit & 7u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "isascii") == 0)
        return (bit & 7u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "isdecimal") == 0)
        return (bit & 1u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "isdigit") == 0)
        return (bit & 7u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "isdisjoint") == 0)
        return (bit & 192u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "isidentifier") == 0)
        return (bit & 1u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "islower") == 0)
        return (bit & 7u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "isnumeric") == 0)
        return (bit & 1u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "isprintable") == 0)
        return (bit & 1u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "isspace") == 0)
        return (bit & 7u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "issubset") == 0)
        return (bit & 192u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "issuperset") == 0)
        return (bit & 192u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "istitle") == 0)
        return (bit & 7u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "isupper") == 0)
        return (bit & 7u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "items") == 0)
        return (bit & 32u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "join") == 0)
        return (bit & 7u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "keys") == 0)
        return (bit & 32u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "ljust") == 0)
        return (bit & 7u) ? ((3 << 8) | 1) : 0;
    if (strcmp(w, "lower") == 0)
        return (bit & 7u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "lstrip") == 0)
        return (bit & 7u) ? ((2 << 8) | 1) : 0;
    if (strcmp(w, "partition") == 0)
        return (bit & 7u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "pop") == 0)
        return (bit & 108u) ? ((3 << 8) | 2) : 0;
    if (strcmp(w, "popitem") == 0)
        return (bit & 32u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "remove") == 0)
        return (bit & 76u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "removeprefix") == 0)
        return (bit & 7u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "removesuffix") == 0)
        return (bit & 7u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "replace") == 0)
        return (bit & 7u) ? ((4 << 8) | 1) : 0;
    if (strcmp(w, "resize") == 0)
        return (bit & 4u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "reverse") == 0)
        return (bit & 12u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "rfind") == 0)
        return (bit & 7u) ? ((4 << 8) | 2) : 0;
    if (strcmp(w, "rindex") == 0)
        return (bit & 7u) ? ((4 << 8) | 2) : 0;
    if (strcmp(w, "rjust") == 0)
        return (bit & 7u) ? ((3 << 8) | 1) : 0;
    if (strcmp(w, "rpartition") == 0)
        return (bit & 7u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "rsplit") == 0)
        return (bit & 7u) ? ((3 << 8) | 2) : 0;
    if (strcmp(w, "rstrip") == 0)
        return (bit & 7u) ? ((2 << 8) | 1) : 0;
    if (strcmp(w, "setdefault") == 0)
        return (bit & 32u) ? ((3 << 8) | 1) : 0;
    if (strcmp(w, "sort") == 0)
        return (bit & 8u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "split") == 0)
        return (bit & 7u) ? ((3 << 8) | 2) : 0;
    if (strcmp(w, "splitlines") == 0)
        return (bit & 7u) ? ((2 << 8) | 1) : 0;
    if (strcmp(w, "startswith") == 0)
        return (bit & 7u) ? ((4 << 8) | 2) : 0;
    if (strcmp(w, "strip") == 0)
        return (bit & 7u) ? ((2 << 8) | 1) : 0;
    if (strcmp(w, "swapcase") == 0)
        return (bit & 7u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "symmetric_difference") == 0)
        return (bit & 192u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "symmetric_difference_update") == 0)
        return (bit & 64u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "title") == 0)
        return (bit & 7u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "to_bytes") == 0)
        return (bit & 256u) ? ((4 << 8) | 3) : 0;
    if (strcmp(w, "translate") == 0)
        return (bit & 7u) ? ((3 << 8) | 1) : 0;
    if (strcmp(w, "union") == 0)
        return (bit & 192u) ? ((2 << 8) | 0) : 0;
    if (strcmp(w, "update") == 0)
        return (bit & 96u) ? ((2 << 8) | 1) : 0;
    if (strcmp(w, "upper") == 0)
        return (bit & 7u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "values") == 0)
        return (bit & 32u) ? ((1 << 8) | 0) : 0;
    if (strcmp(w, "zfill") == 0)
        return (bit & 7u) ? ((2 << 8) | 0) : 0;
    return 0;
}

/* THE PARAMETER NAMES A KEYWORD MAY USE, and the value each slot
   defaults to, for the methods CPython gives a keyword signature.

   GENERATED from `METHOD_PARAMS`, which is the same table the
   frontend folds the WRITTEN spelling against -- so `x.split(",",
   maxsplit=1)` and `f = x.split` then `f(",", maxsplit=1)` are one
   arrangement rather than two that can drift.

   Answers the count, or 0 for a name with no keyword signature at
   all. `names[i]` is 0 for a parameter CPython marks positional
   only; `defs[i]` is 0 for one with no default. */
static int64_t apy_kind_meth_sign(const char *w, apy_value *names,
                                  apy_value *defs) {
    if (strcmp(w, "decode") == 0) {
        names[0] = apy_lit("encoding"); defs[0] = apy_lit("utf-8");
        names[1] = apy_lit("errors"); defs[1] = apy_lit("strict");
        return 2;
    }
    if (strcmp(w, "encode") == 0) {
        names[0] = apy_lit("encoding"); defs[0] = apy_lit("utf-8");
        names[1] = apy_lit("errors"); defs[1] = apy_lit("strict");
        return 2;
    }
    if (strcmp(w, "expandtabs") == 0) {
        names[0] = apy_lit("tabsize"); defs[0] = apy_from_int(8);
        return 1;
    }
    if (strcmp(w, "replace") == 0) {
        names[0] = 0; defs[0] = 0;
        names[1] = 0; defs[1] = 0;
        names[2] = apy_lit("count"); defs[2] = apy_from_int(-1);
        return 3;
    }
    if (strcmp(w, "rsplit") == 0) {
        names[0] = apy_lit("sep"); defs[0] = apy_none();
        names[1] = apy_lit("maxsplit"); defs[1] = apy_from_int(-1);
        return 2;
    }
    if (strcmp(w, "split") == 0) {
        names[0] = apy_lit("sep"); defs[0] = apy_none();
        names[1] = apy_lit("maxsplit"); defs[1] = apy_from_int(-1);
        return 2;
    }
    if (strcmp(w, "splitlines") == 0) {
        names[0] = apy_lit("keepends"); defs[0] = apy_from_bool(0);
        return 1;
    }
    if (strcmp(w, "to_bytes") == 0) {
        names[0] = apy_lit("length"); defs[0] = apy_from_int(1);
        names[1] = apy_lit("byteorder"); defs[1] = apy_lit("big");
        names[2] = apy_lit("signed"); defs[2] = apy_from_bool(0);
        return 3;
    }
    if (strcmp(w, "translate") == 0) {
        names[0] = 0; defs[0] = 0;
        names[1] = apy_lit("delete"); defs[1] = apy_bytes_literal((apy_value)"", 0);
        return 2;
    }
    return 0;
}

/* Does CPython WRITE this dunder out for a receiver of kind `bit`,
   rather than filling a slot with it? That is the whole of what
   tells `builtin_function_or_method` from `method-wrapper`, and it
   is not derivable from the signature -- see `written_rows` in the
   generator. */
static int64_t apy_kind_meth_written(const char *w, unsigned bit) {
    if (strcmp(w, "__alloc__") == 0)
        return (bit & 4u) ? 1 : 0;
    if (strcmp(w, "__bytes__") == 0)
        return (bit & 2u) ? 1 : 0;
    if (strcmp(w, "__ceil__") == 0)
        return (bit & 768u) ? 1 : 0;
    if (strcmp(w, "__class_getitem__") == 0)
        return (bit & 4344u) ? 1 : 0;
    if (strcmp(w, "__complex__") == 0)
        return (bit & 2048u) ? 1 : 0;
    if (strcmp(w, "__contains__") == 0)
        return (bit & 224u) ? 1 : 0;
    if (strcmp(w, "__dir__") == 0)
        return (bit & 8191u) ? 1 : 0;
    if (strcmp(w, "__enter__") == 0)
        return (bit & 4096u) ? 1 : 0;
    if (strcmp(w, "__exit__") == 0)
        return (bit & 4096u) ? 1 : 0;
    if (strcmp(w, "__floor__") == 0)
        return (bit & 768u) ? 1 : 0;
    if (strcmp(w, "__format__") == 0)
        return (bit & 8191u) ? 1 : 0;
    if (strcmp(w, "__getformat__") == 0)
        return (bit & 512u) ? 1 : 0;
    if (strcmp(w, "__getitem__") == 0)
        return (bit & 40u) ? 1 : 0;
    if (strcmp(w, "__getnewargs__") == 0)
        return (bit & 2835u) ? 1 : 0;
    if (strcmp(w, "__getstate__") == 0)
        return (bit & 8191u) ? 1 : 0;
    if (strcmp(w, "__init_subclass__") == 0)
        return (bit & 8191u) ? 1 : 0;
    if (strcmp(w, "__new__") == 0)
        return (bit & 8191u) ? 1 : 0;
    if (strcmp(w, "__reduce__") == 0)
        return (bit & 8191u) ? 1 : 0;
    if (strcmp(w, "__reduce_ex__") == 0)
        return (bit & 8191u) ? 1 : 0;
    if (strcmp(w, "__reversed__") == 0)
        return (bit & 1064u) ? 1 : 0;
    if (strcmp(w, "__round__") == 0)
        return (bit & 768u) ? 1 : 0;
    if (strcmp(w, "__sizeof__") == 0)
        return (bit & 8191u) ? 1 : 0;
    if (strcmp(w, "__subclasshook__") == 0)
        return (bit & 8191u) ? 1 : 0;
    if (strcmp(w, "__trunc__") == 0)
        return (bit & 768u) ? 1 : 0;
    return 0;
}

/* One builtin method call, by name and by the count that arrived.
   The irregular shapes are mirrored from `_dyn_builtin_method`; see
   the generator. Answers 0 having raised for an arity no entry
   point serves, which is how a receiver's own kind refuses a form
   another kind admits. */
static apy_value apy_kind_meth_call(const char *w, apy_value *a,
                                    int64_t n) {
    if (strcmp(w, "add") == 0) {
        if (n >= 2) return apy_set_add(a[0], a[1]);
    }
    if (strcmp(w, "append") == 0) {
        if (n >= 2) return apy_seq_push(a[0], a[1]);
    }
    if (strcmp(w, "as_integer_ratio") == 0) {
        if (n >= 1) return apy_as_integer_ratio(a[0]);
    }
    if (strcmp(w, "bit_count") == 0) {
        if (n >= 1) return apy_bit_count(a[0]);
    }
    if (strcmp(w, "bit_length") == 0) {
        if (n >= 1) return apy_bit_length(a[0]);
    }
    if (strcmp(w, "capitalize") == 0) {
        if (n >= 1) return apy_str_capitalize(a[0]);
    }
    if (strcmp(w, "casefold") == 0) {
        if (n >= 1) return apy_str_casefold(a[0]);
    }
    if (strcmp(w, "center") == 0) {
        if (n >= 3) return apy_str_center_fill(a[0], a[1], a[2]);
        if (n >= 2) return apy_str_center(a[0], a[1]);
    }
    if (strcmp(w, "clear") == 0) {
        if (n >= 1) return apy_clear(a[0]);
    }
    if (strcmp(w, "conjugate") == 0) {
        if (n >= 1) return apy_conjugate(a[0]);
    }
    if (strcmp(w, "copy") == 0) {
        if (n >= 1) return apy_copy(a[0]);
    }
    if (strcmp(w, "count") == 0) {
        if (n >= 4) return apy_str_count3(a[0], a[1], a[2], a[3]);
        if (n >= 3) return apy_str_count2(a[0], a[1], a[2]);
        if (n >= 2) return apy_count_of(a[0], a[1]);
    }
    if (strcmp(w, "decode") == 0) {
        if (n >= 3) return apy_bytes_decode(a[0], a[1], a[2]);
        if (n >= 2) return apy_bytes_decode(a[0], a[1], apy_none());
        if (n >= 1) return apy_bytes_decode(a[0], apy_none(), apy_none());
    }
    if (strcmp(w, "difference") == 0) {
        if (n >= 2) return apy_set_difference(a[0], a[1]);
    }
    if (strcmp(w, "difference_update") == 0) {
        if (n >= 2) return apy_set_diff_update(a[0], a[1]);
    }
    if (strcmp(w, "discard") == 0) {
        if (n >= 2) return apy_set_discard(a[0], a[1]);
    }
    if (strcmp(w, "encode") == 0) {
        if (n >= 3) return apy_str_encode(a[0], a[1], a[2]);
        if (n >= 2) return apy_str_encode(a[0], a[1], apy_none());
        if (n >= 1) return apy_str_encode(a[0], apy_none(), apy_none());
    }
    if (strcmp(w, "endswith") == 0) {
        if (n >= 4) return apy_str_endswith3(a[0], a[1], a[2], a[3]);
        if (n >= 3) return apy_str_endswith2(a[0], a[1], a[2]);
        if (n >= 2) return apy_str_endswith(a[0], a[1]);
    }
    if (strcmp(w, "expandtabs") == 0) {
        if (n >= 2) return apy_str_expandtabs(a[0], a[1]);
        if (n >= 1) return apy_str_expandtabs(a[0], apy_from_int(8));
    }
    if (strcmp(w, "extend") == 0) {
        if (n >= 2) return apy_extend(a[0], a[1]);
    }
    if (strcmp(w, "find") == 0) {
        if (n >= 4) return apy_str_find3(a[0], a[1], a[2], a[3]);
        if (n >= 3) return apy_str_find2(a[0], a[1], a[2]);
        if (n >= 2) return apy_str_find(a[0], a[1]);
    }
    if (strcmp(w, "format_map") == 0) {
        if (n >= 2) return apy_str_format_map(a[0], a[1]);
    }
    if (strcmp(w, "get") == 0) {
        if (n >= 3) return apy_dict_get_or(a[0], a[1], a[2]);
        if (n >= 2) return apy_dict_get_or(a[0], a[1], apy_none());
    }
    if (strcmp(w, "hex") == 0) {
        if (n >= 2) return apy_bytes_hex(a[0], a[1]);
        if (n >= 1) return apy_hex_of(a[0], apy_none());
    }
    if (strcmp(w, "index") == 0) {
        if (n >= 4) return apy_index_of3(a[0], a[1], a[2], a[3]);
        if (n >= 3) return apy_index_of2(a[0], a[1], a[2]);
        if (n >= 2) return apy_index_of(a[0], a[1]);
    }
    if (strcmp(w, "insert") == 0) {
        if (n >= 3) return apy_list_insert(a[0], a[1], a[2]);
    }
    if (strcmp(w, "intersection") == 0) {
        if (n >= 2) return apy_set_intersection(a[0], a[1]);
    }
    if (strcmp(w, "intersection_update") == 0) {
        if (n >= 2) return apy_set_inter_update(a[0], a[1]);
    }
    if (strcmp(w, "is_integer") == 0) {
        if (n >= 1) return apy_is_integer(a[0]);
    }
    if (strcmp(w, "isalnum") == 0) {
        if (n >= 1) return apy_str_isalnum(a[0]);
    }
    if (strcmp(w, "isalpha") == 0) {
        if (n >= 1) return apy_str_isalpha(a[0]);
    }
    if (strcmp(w, "isascii") == 0) {
        if (n >= 1) return apy_str_isascii(a[0]);
    }
    if (strcmp(w, "isdecimal") == 0) {
        if (n >= 1) return apy_str_isdecimal(a[0]);
    }
    if (strcmp(w, "isdigit") == 0) {
        if (n >= 1) return apy_str_isdigit(a[0]);
    }
    if (strcmp(w, "isdisjoint") == 0) {
        if (n >= 2) return apy_set_isdisjoint(a[0], a[1]);
    }
    if (strcmp(w, "isidentifier") == 0) {
        if (n >= 1) return apy_str_isidentifier(a[0]);
    }
    if (strcmp(w, "islower") == 0) {
        if (n >= 1) return apy_str_islower(a[0]);
    }
    if (strcmp(w, "isnumeric") == 0) {
        if (n >= 1) return apy_str_isnumeric(a[0]);
    }
    if (strcmp(w, "isprintable") == 0) {
        if (n >= 1) return apy_str_isprintable(a[0]);
    }
    if (strcmp(w, "isspace") == 0) {
        if (n >= 1) return apy_str_isspace(a[0]);
    }
    if (strcmp(w, "issubset") == 0) {
        if (n >= 2) return apy_set_issubset(a[0], a[1]);
    }
    if (strcmp(w, "issuperset") == 0) {
        if (n >= 2) return apy_set_issuperset(a[0], a[1]);
    }
    if (strcmp(w, "istitle") == 0) {
        if (n >= 1) return apy_str_istitle(a[0]);
    }
    if (strcmp(w, "isupper") == 0) {
        if (n >= 1) return apy_str_isupper(a[0]);
    }
    if (strcmp(w, "items") == 0) {
        if (n >= 1) return apy_dict_parts(a[0], 2);
    }
    if (strcmp(w, "join") == 0) {
        if (n >= 2) return apy_str_join(a[0], a[1]);
    }
    if (strcmp(w, "keys") == 0) {
        if (n >= 1) return apy_dict_parts(a[0], 0);
    }
    if (strcmp(w, "ljust") == 0) {
        if (n >= 3) return apy_str_ljust_fill(a[0], a[1], a[2]);
        if (n >= 2) return apy_str_ljust(a[0], a[1]);
    }
    if (strcmp(w, "lower") == 0) {
        if (n >= 1) return apy_str_lower(a[0]);
    }
    if (strcmp(w, "lstrip") == 0) {
        if (n >= 2) return apy_str_lstrip_chars(a[0], a[1]);
        if (n >= 1) return apy_str_lstrip(a[0]);
    }
    if (strcmp(w, "partition") == 0) {
        if (n >= 2) return apy_str_partition(a[0], a[1]);
    }
    if (strcmp(w, "pop") == 0) {
        if (n >= 3) return apy_pop_or(a[0], a[1], a[2]);
        if (n >= 2) return apy_list_pop(a[0], a[1], 1);
        if (n >= 1) return apy_list_pop(a[0], apy_none(), 0);
    }
    if (strcmp(w, "popitem") == 0) {
        if (n >= 1) return apy_dict_popitem(a[0]);
    }
    if (strcmp(w, "remove") == 0) {
        if (n >= 2) return apy_list_remove(a[0], a[1]);
    }
    if (strcmp(w, "removeprefix") == 0) {
        if (n >= 2) return apy_str_removeprefix(a[0], a[1]);
    }
    if (strcmp(w, "removesuffix") == 0) {
        if (n >= 2) return apy_str_removesuffix(a[0], a[1]);
    }
    if (strcmp(w, "replace") == 0) {
        if (n >= 4) return apy_str_replace_n(a[0], a[1], a[2], a[3]);
        if (n >= 3) return apy_str_replace(a[0], a[1], a[2]);
    }
    if (strcmp(w, "resize") == 0) {
        if (n >= 2) return apy_bytearray_resize(a[0], a[1]);
    }
    if (strcmp(w, "reverse") == 0) {
        if (n >= 1) return apy_list_reverse(a[0]);
    }
    if (strcmp(w, "rfind") == 0) {
        if (n >= 4) return apy_str_rfind3(a[0], a[1], a[2], a[3]);
        if (n >= 3) return apy_str_rfind2(a[0], a[1], a[2]);
        if (n >= 2) return apy_str_rfind(a[0], a[1]);
    }
    if (strcmp(w, "rindex") == 0) {
        if (n >= 4) return apy_str_rindex3(a[0], a[1], a[2], a[3]);
        if (n >= 3) return apy_str_rindex2(a[0], a[1], a[2]);
        if (n >= 2) return apy_str_rindex(a[0], a[1]);
    }
    if (strcmp(w, "rjust") == 0) {
        if (n >= 3) return apy_str_rjust_fill(a[0], a[1], a[2]);
        if (n >= 2) return apy_str_rjust(a[0], a[1]);
    }
    if (strcmp(w, "rpartition") == 0) {
        if (n >= 2) return apy_str_rpartition(a[0], a[1]);
    }
    if (strcmp(w, "rsplit") == 0) {
        if (n >= 3) return apy_str_rsplit_n(a[0], a[1], a[2]);
        if (n >= 2) return apy_str_rsplit(a[0], a[1]);
        if (n >= 1) return apy_str_rsplit_ws(a[0]);
    }
    if (strcmp(w, "rstrip") == 0) {
        if (n >= 2) return apy_str_rstrip_chars(a[0], a[1]);
        if (n >= 1) return apy_str_rstrip(a[0]);
    }
    if (strcmp(w, "setdefault") == 0) {
        if (n >= 3) return apy_setdefault(a[0], a[1], a[2]);
        if (n >= 2) return apy_setdefault(a[0], a[1], apy_none());
    }
    if (strcmp(w, "sort") == 0) {
        if (n >= 1) return apy_list_sort(a[0], apy_none(), apy_from_bool(0));
    }
    if (strcmp(w, "split") == 0) {
        if (n >= 3) return apy_str_split_n(a[0], a[1], a[2]);
        if (n >= 2) return apy_split_of(a[0], a[1]);
        if (n >= 1) return apy_str_split_ws(a[0]);
    }
    if (strcmp(w, "splitlines") == 0) {
        if (n >= 2) return apy_str_splitlines_keep(a[0], a[1]);
        if (n >= 1) return apy_str_splitlines(a[0]);
    }
    if (strcmp(w, "startswith") == 0) {
        if (n >= 4) return apy_str_startswith3(a[0], a[1], a[2], a[3]);
        if (n >= 3) return apy_str_startswith2(a[0], a[1], a[2]);
        if (n >= 2) return apy_str_startswith(a[0], a[1]);
    }
    if (strcmp(w, "strip") == 0) {
        if (n >= 2) return apy_str_strip_chars(a[0], a[1]);
        if (n >= 1) return apy_str_strip(a[0]);
    }
    if (strcmp(w, "swapcase") == 0) {
        if (n >= 1) return apy_str_swapcase(a[0]);
    }
    if (strcmp(w, "symmetric_difference") == 0) {
        if (n >= 2) return apy_set_symdiff(a[0], a[1]);
    }
    if (strcmp(w, "symmetric_difference_update") == 0) {
        if (n >= 2) return apy_set_symdiff_update(a[0], a[1]);
    }
    if (strcmp(w, "title") == 0) {
        if (n >= 1) return apy_str_title(a[0]);
    }
    if (strcmp(w, "to_bytes") == 0) {
        if (n >= 4) return apy_to_bytes_n(a[0], a[1], a[2], a[3]);
        if (n >= 3) return apy_to_bytes_n(a[0], a[1], a[2], apy_from_bool(0));
        if (n >= 2) return apy_to_bytes_n(a[0], a[1], apy_lit("big"), apy_from_bool(0));
        if (n >= 1) return apy_to_bytes_n(a[0], apy_from_int(1), apy_lit("big"), apy_from_bool(0));
    }
    if (strcmp(w, "translate") == 0) {
        if (n >= 3) return apy_bytes_translate(a[0], a[1], a[2]);
        if (n >= 2) return apy_str_translate(a[0], a[1]);
    }
    if (strcmp(w, "union") == 0) {
        if (n >= 2) return apy_set_union(a[0], a[1]);
    }
    if (strcmp(w, "update") == 0) {
        if (n >= 2) return apy_update(a[0], a[1]);
        if (n >= 1) return apy_update(a[0], apy_dict_new(1));
    }
    if (strcmp(w, "upper") == 0) {
        if (n >= 1) return apy_str_upper(a[0]);
    }
    if (strcmp(w, "values") == 0) {
        if (n >= 1) return apy_dict_parts(a[0], 1);
    }
    if (strcmp(w, "zfill") == 0) {
        if (n >= 2) return apy_str_zfill(a[0], a[1]);
    }
    return apy_fail2("TypeError", "'%s' is not a builtin method%s",
                     w, "");
}
/* THE DOCSTRING OF THE TYPE A VALUE IS, by that type's name.

   GENERATED by `objects/c/_gen_kindmeth.py` from CPython's own
   `__doc__`, which is where the answer is: the text is CPython's
   and not a fact this compiler could derive. Answers 0 for a kind
   with none, which the caller reads as "not this". */
static const char *apy_kind_doc(const char *kind) {
    if (strcmp(kind, "str") == 0)
        return "str(object='') -> str\n"
               "str(bytes_or_buffer[, encoding[, errors]]) -> str\n"
               "\n"
               "Create a new string object from the given object. If encoding or\n"
               "errors is specified, then the object must expose a data buffer\n"
               "that will be decoded using the given encoding and error handler.\n"
               "Otherwise, returns the result of object.__str__() (if defined)\n"
               "or repr(object).\n"
               "encoding defaults to 'utf-8'.\n"
               "errors defaults to 'strict'.";
    if (strcmp(kind, "bytes") == 0)
        return "bytes(iterable_of_ints) -> bytes\n"
               "bytes(string, encoding[, errors]) -> bytes\n"
               "bytes(bytes_or_buffer) -> immutable copy of bytes_or_buffer\n"
               "bytes(int) -> bytes object of size given by the parameter initialized with null bytes\n"
               "bytes() -> empty bytes object\n"
               "\n"
               "Construct an immutable array of bytes from:\n"
               "  - an iterable yielding integers in range(256)\n"
               "  - a text string encoded using the specified encoding\n"
               "  - any object implementing the buffer API.\n"
               "  - an integer";
    if (strcmp(kind, "bytearray") == 0)
        return "bytearray(iterable_of_ints) -> bytearray\n"
               "bytearray(string, encoding[, errors]) -> bytearray\n"
               "bytearray(bytes_or_buffer) -> mutable copy of bytes_or_buffer\n"
               "bytearray(int) -> bytes array of size given by the parameter initialized with null bytes\n"
               "bytearray() -> empty bytes array\n"
               "\n"
               "Construct a mutable bytearray object from:\n"
               "  - an iterable yielding integers in range(256)\n"
               "  - a text string encoded using the specified encoding\n"
               "  - a bytes or a buffer object\n"
               "  - any object implementing the buffer API.\n"
               "  - an integer";
    if (strcmp(kind, "list") == 0)
        return "Built-in mutable sequence.\n"
               "\n"
               "If no argument is given, the constructor creates a new empty list.\n"
               "The argument must be an iterable if specified.";
    if (strcmp(kind, "tuple") == 0)
        return "Built-in immutable sequence.\n"
               "\n"
               "If no argument is given, the constructor returns an empty tuple.\n"
               "If iterable is specified the tuple is initialized from iterable's items.\n"
               "\n"
               "If the argument is a tuple, the return value is the same object.";
    if (strcmp(kind, "dict") == 0)
        return "dict() -> new empty dictionary\n"
               "dict(mapping) -> new dictionary initialized from a mapping object's\n"
               "    (key, value) pairs\n"
               "dict(iterable) -> new dictionary initialized as if via:\n"
               "    d = {}\n"
               "    for k, v in iterable:\n"
               "        d[k] = v\n"
               "dict(**kwargs) -> new dictionary initialized with the name=value pairs\n"
               "    in the keyword argument list.  For example:  dict(one=1, two=2)";
    if (strcmp(kind, "set") == 0)
        return "Build an unordered collection of unique elements.";
    if (strcmp(kind, "frozenset") == 0)
        return "Build an immutable unordered collection of unique elements.";
    if (strcmp(kind, "int") == 0)
        return "int([x]) -> integer\n"
               "int(x, base=10) -> integer\n"
               "\n"
               "Convert a number or string to an integer, or return 0 if no arguments\n"
               "are given.  If x is a number, return x.__int__().  For floating-point\n"
               "numbers, this truncates towards zero.\n"
               "\n"
               "If x is not a number or if base is given, then x must be a string,\n"
               "bytes, or bytearray instance representing an integer literal in the\n"
               "given base.  The literal can be preceded by '+' or '-' and be surrounded\n"
               "by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.\n"
               "Base 0 means to interpret the base from the string as an integer literal.\n"
               ">>> int('0b100', base=0)\n"
               "4";
    if (strcmp(kind, "float") == 0)
        return "Convert a string or number to a floating-point number, if possible.";
    if (strcmp(kind, "range") == 0)
        return "range(stop) -> range object\n"
               "range(start, stop[, step]) -> range object\n"
               "\n"
               "Return an object that produces a sequence of integers from start (inclusive)\n"
               "to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.\n"
               "start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.\n"
               "These are exactly the valid indices for a list of 4 elements.\n"
               "When step is given, it specifies the increment (or decrement).";
    if (strcmp(kind, "complex") == 0)
        return "Create a complex number from a string or numbers.\n"
               "\n"
               "If a string is given, parse it as a complex number.\n"
               "If a single number is given, convert it to a complex number.\n"
               "If the 'real' or 'imag' arguments are given, create a complex number\n"
               "with the specified real and imaginary components.";
    if (strcmp(kind, "memoryview") == 0)
        return "Create a new memoryview object which references the given object.";
    if (strcmp(kind, "bool") == 0)
        return "Returns True when the argument is true, False otherwise.\n"
               "The builtins True and False are the only two instances of the class bool.\n"
               "The class bool is a subclass of the class int, and cannot be subclassed.";
    if (strcmp(kind, "NoneType") == 0)
        return "The type of the None singleton.";
    return 0;
}
"""
