name: Rename beta branch

on:
  push:
    branches: [beta]
    paths:
      - ".github/workflows/rename-beta-branch.yml"
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rename:
    if: github.head_ref == 'beta' || github.ref_name == 'beta'
    runs-on: ubuntu-24.04
    steps:
      - name: Rename beta to beta/3.14.0
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api --method POST \
            "repos/${{ github.repository }}/branches/beta/rename" \
            -f new_name='beta/3.14.0'
